import type { LectureFormValues } from '@/features/lecture/validation/lectureFormSchema'

export const lectureCreateFormDefaultValues: LectureFormValues = {
  lectureName: '',
  lectureLoc: 'ONLINE',
  location: null,
  days: [],
  startTime: '09:00',
  endTime: '18:00',
  recruitProcedures: [{ type: 'DOCUMENT' }],
  recruitType: 'GENERAL',
  subsidy: 0,
  lectureFee: 0,
  eduSubsidy: 0,
  goal: null,
  maxCapacity: null,
  equipPc: null,
  equipMerit: null,
  books: false,
  resume: false,
  mockInterview: false,
  employmentHelp: false,
  afterCompletion: false,
  url: null,
  lectureImageFile: null,
  startAtDate: new Date(),
  endAtDate: new Date(),
  deadlineDate: null,
  totalDays: 1,
  totalTimes: 1,
  projectNum: null,
  projectTime: null,
  projectTeam: null,
  projectTool: null,
  projectMentor: false,

  quals: [],
  teachers: [],
  adds: [],

  categoryId: null,
  curriculums: [],
}
