export { LectureCreateAddsFields } from '@/features/lecture/components/lecture-create/sections/adds-fields'
export { LectureCreateBasicInfoFields } from '@/features/lecture/components/lecture-create/sections/basic-info-fields'
export { LectureCreateCategoryFields } from '@/features/lecture/components/lecture-create/sections/category-fields'
export { LectureCreateCostFields } from '@/features/lecture/components/lecture-create/sections/cost-fields'
export { LectureCreateCurriculumFields } from '@/features/lecture/components/lecture-create/sections/curriculum-fields'
export { LectureCreateEquipmentFields } from '@/features/lecture/components/lecture-create/sections/equipment-fields'
export { LectureCreateLocationFields } from '@/features/lecture/components/lecture-create/sections/location-fields'
export { LectureCreateOptionsFields } from '@/features/lecture/components/lecture-create/sections/options-fields'
export { LectureCreateProjectFields } from '@/features/lecture/components/lecture-create/sections/project-fields'
export { LectureCreateQualificationFields } from '@/features/lecture/components/lecture-create/sections/qualification-fields'
export { LectureCreateRecruitProcedureFields } from '@/features/lecture/components/lecture-create/sections/recruit-procedure-fields'
export { LectureCreateScheduleFields } from '@/features/lecture/components/lecture-create/sections/schedule-fields'
export { LectureCreateTeachersFields } from '@/features/lecture/components/lecture-create/sections/teachers-fields'
export { LectureCreateSpecialCurriculumFields } from '@/features/lecture/components/lecture-create/sections/special-curriculum-fields'

export { lectureCreateFormDefaultValues } from '@/features/lecture/components/lecture-create/default-values'

