export { LectureCreateAddsFields } from '@/features/lecture/components/lecture-create/sections/AddsFields'
export { LectureCreateBasicInfoFields } from '@/features/lecture/components/lecture-create/sections/BasicInfoFields'
export { LectureCreateCategoryFields } from '@/features/lecture/components/lecture-create/sections/CategoryFields'
export { LectureCreateCostFields } from '@/features/lecture/components/lecture-create/sections/CostFields'
export { LectureCreateCurriculumFields } from '@/features/lecture/components/lecture-create/sections/CurriculumFields'
export { LectureCreateEquipmentFields } from '@/features/lecture/components/lecture-create/sections/EquipmentFields'
export { LectureCreateLocationFields } from '@/features/lecture/components/lecture-create/sections/LocationFields'
export { LectureCreateOptionsFields } from '@/features/lecture/components/lecture-create/sections/OptionsFields'
export { LectureCreateProjectFields } from '@/features/lecture/components/lecture-create/sections/ProjectFields'
export { LectureCreateQualificationFields } from '@/features/lecture/components/lecture-create/sections/QualificationFields'
export { LectureCreateRecruitProcedureFields } from '@/features/lecture/components/lecture-create/sections/RecruitProcedureFields'
export { LectureCreateScheduleFields } from '@/features/lecture/components/lecture-create/sections/ScheduleFields'
export { LectureCreateTeachersFields } from '@/features/lecture/components/lecture-create/sections/TeachersFields'

export { lectureCreateFormDefaultValues } from '@/features/lecture/components/lecture-create/defaultValues'

