import { Course } from '@/features/course/types/course.type'

export const mockCourses: Course[] = [
  {
    id: 1,
    title: '프론트엔드 실전 웹 서비스 개발 Bootcamp',
    organization: '멋쟁이사자처럼',
    periodStart: '2024-02-01',
    periodEnd: '2024-04-30',
    tags: [{ id: 1, name: '웹개발' }],
    imageUrl: 'https://picsum.photos/seed/web1/300/200',
  },
  {
    id: 2,
    title: '모바일 앱 개발(Android/Kotlin) 실무 과정',
    organization: '패스트캠퍼스',
    periodStart: '2024-03-15',
    periodEnd: '2024-06-20',
    tags: [{ id: 2, name: '모바일' }],
    imageUrl: 'https://picsum.photos/seed/mobile2/300/200',
  },
  {
    id: 3,
    title: 'Unity 기반 게임 개발 & 블록체인 연동 심화 과정',
    organization: '멋쟁이사자처럼',
    periodStart: '2024-01-20',
    periodEnd: '2024-04-10',
    tags: [{ id: 3, name: '게임·블록체인' }],
    imageUrl: 'https://picsum.photos/seed/game3/300/200',
  },
  {
    id: 4,
    title: 'AI 모델링 기반 데이터 분석 Bootcamp',
    organization: '코드스테이츠',
    periodStart: '2024-01-10',
    periodEnd: '2024-03-01',
    tags: [{ id: 4, name: '데이터·AI' }],
    imageUrl: 'https://picsum.photos/seed/ai4/300/200',
  },
  {
    id: 5,
    title: '백엔드 엔지니어 양성과정',
    organization: '멋쟁이사자처럼',
    periodStart: '2024-03-01',
    periodEnd: '2024-06-30',
    tags: [{ id: 5, name: '백엔드' }],
    imageUrl: 'https://picsum.photos/seed/backend5/300/200',
  },
  {
    id: 6,
    title: '클라우드 엔지니어링 실무 과정',
    organization: '패스트캠퍼스',
    periodStart: '2024-04-01',
    periodEnd: '2024-07-31',
    tags: [{ id: 6, name: '클라우드' }],
    imageUrl: 'https://picsum.photos/seed/cloud6/300/200',
  },
  {
    id: 7,
    title: '풀스택 개발자 부트캠프',
    organization: '코드스테이츠',
    periodStart: '2024-02-15',
    periodEnd: '2024-05-15',
    tags: [{ id: 7, name: '풀스택' }],
    imageUrl: 'https://picsum.photos/seed/fullstack7/300/200',
  },
  {
    id: 8,
    title: '데이터 사이언스 집중 과정',
    organization: '코드스테이츠',
    periodStart: '2024-03-10',
    periodEnd: '2024-06-10',
    tags: [{ id: 8, name: '데이터·AI' }],
    imageUrl: 'https://picsum.photos/seed/data8/300/200',
  },
]
